Repository paion-data/ci-cd-core, pull requests merged in 2024-04, with the labels that each got.

#5 Make script executable
  .github/tag-for-release.bash
Labels: BUG, NEED 1 REVIEW

#9 Supplement cypress
  .github/workflows/cypress-e2e.yml
Labels: NEED 1 REVIEW

#10 Add the type field to inputs.ndoe-version in the ui-code-style.yml file
  .github/workflows/ui-code-style.yml
Labels: BUG, MERGEABLE

#11 Fix UI code style
  .github/workflows/ui-code-style.yml
Labels: NEED 1 REVIEW

#12 Simplify E2E workflow config
  .github/workflows/cypress-e2e.yml
  docs/docs/cypress-e2e.md
  docs/docs/ui-code-style.md
  docs/docs/ui-unit-test.md
Labels: BREAKING CHANGE, DOCUMENTATION, NEED 1 REVIEW, REFACTORING

#13 Enhance documentations
  .github/pull_request_template.md
  .github/version-bump/tag-for-release.bash
  .github/version-bump/upversion.py
  .github/workflows/cicd.yml
  .github/workflows/npm-release.yml
  .github/workflows/ui-code-style.yml
  .github/workflows/ui-unit-test.yml
  .github/workflows/version-bump.yml
  .github/workflows/yml-md-style-and-link-checks.yml
  .github/yml-md-style-and-link-checks/.lycheeignore
  .github/yml-md-style-and-link-checks/.mdlrc
  .github/yml-md-style-and-link-checks/.yamllint
  .github/yml-md-style-and-link-checks/markdownlint.rb
  docs/docs/version-bump.md
  docs/docs/yml-md-style-and-link-checks.md
Labels: NEED 1 REVIEW

#14 Turn md & yml style check back on
  .github/workflows/cicd.yml
  .mdlrc
  .yamllint
  docs/docs/yml-md-style-and-link-checks.md
  markdownlint.rb
Labels: CI/CD, CONFIG, NEED 1 REVIEW

#15 Documenting version bump with permission check
  docs/docs/img/permission.png
  docs/docs/version-bump.md
Labels: DOCUMENTATION, NEED 1 REVIEW

#16 add inputs.node-version into a array
  .github/workflows/cypress-e2e.yml
Labels: NEED 1 REVIEW
